/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class tecx extends javax.swing.JFrame {

    /**
     * Creates new form tecx
     */
    public tecx() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        to = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tabto = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        astudents = new javax.swing.JCheckBox();
        afirst = new javax.swing.JCheckBox();
        asecond = new javax.swing.JCheckBox();
        athird = new javax.swing.JCheckBox();
        afourth = new javax.swing.JCheckBox();
        airreg = new javax.swing.JCheckBox();
        acrim = new javax.swing.JCheckBox();
        aeduc = new javax.swing.JCheckBox();
        aitct = new javax.swing.JCheckBox();
        absba = new javax.swing.JCheckBox();
        afi = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        ins_all = new javax.swing.JCheckBox();
        ins_parttime = new javax.swing.JCheckBox();
        ins_regular = new javax.swing.JCheckBox();
        ins_crim = new javax.swing.JCheckBox();
        ins_educ = new javax.swing.JCheckBox();
        ins_itct = new javax.swing.JCheckBox();
        ins_bsba = new javax.swing.JCheckBox();
        ins_fi = new javax.swing.JCheckBox();
        ins_staff = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        officers_all = new javax.swing.JCheckBox();
        ossg = new javax.swing.JCheckBox();
        ouso = new javax.swing.JCheckBox();
        oaquarian = new javax.swing.JCheckBox();
        orotc = new javax.swing.JCheckBox();
        oclass = new javax.swing.JCheckBox();
        oassap = new javax.swing.JCheckBox();
        oteso = new javax.swing.JCheckBox();
        ofiso = new javax.swing.JCheckBox();
        owbm = new javax.swing.JCheckBox();
        opsits = new javax.swing.JCheckBox();
        ocrim = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        tx_all = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();

        to.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        to.setBackground(new java.awt.Color(204, 204, 204));
        to.setMinimumSize(new java.awt.Dimension(648, 478));
        to.setModal(true);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("TO:");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("MESSAGE");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jTextPane1.setBackground(new java.awt.Color(204, 255, 255));
        jTextPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), new java.awt.Color(2, 2, 63), new java.awt.Color(51, 51, 51)));
        jTextPane1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextPane1.setToolTipText("write your text message here");
        jScrollPane1.setViewportView(jTextPane1);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Send");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("CANCEL");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 475, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jLabel1, jLabel2, jLabel3});

        javax.swing.GroupLayout toLayout = new javax.swing.GroupLayout(to.getContentPane());
        to.getContentPane().setLayout(toLayout);
        toLayout.setHorizontalGroup(
            toLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        toLayout.setVerticalGroup(
            toLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RECIPIENT");
        setMinimumSize(new java.awt.Dimension(538, 445));

        tabto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        tabto.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tabto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabtoMouseClicked(evt);
            }
        });

        astudents.setBackground(new java.awt.Color(252, 227, 242));
        astudents.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        astudents.setForeground(new java.awt.Color(51, 0, 51));
        astudents.setText("ALL STUDENT");
        astudents.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        astudents.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        astudents.setIconTextGap(10);
        astudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                astudentsMouseClicked(evt);
            }
        });
        astudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                astudentsActionPerformed(evt);
            }
        });

        afirst.setBackground(new java.awt.Color(252, 227, 242));
        afirst.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        afirst.setForeground(new java.awt.Color(51, 0, 51));
        afirst.setText("ALL FIRST YEAR");
        afirst.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        afirst.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        afirst.setIconTextGap(10);
        afirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afirstActionPerformed(evt);
            }
        });

        asecond.setBackground(new java.awt.Color(252, 227, 242));
        asecond.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        asecond.setForeground(new java.awt.Color(51, 0, 51));
        asecond.setText("ALL SECOND YEAR");
        asecond.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        asecond.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        asecond.setIconTextGap(10);
        asecond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asecondActionPerformed(evt);
            }
        });

        athird.setBackground(new java.awt.Color(252, 227, 242));
        athird.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        athird.setForeground(new java.awt.Color(51, 0, 51));
        athird.setText("ALL THIRD YEAR");
        athird.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        athird.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        athird.setIconTextGap(10);
        athird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                athirdActionPerformed(evt);
            }
        });

        afourth.setBackground(new java.awt.Color(252, 227, 242));
        afourth.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        afourth.setForeground(new java.awt.Color(51, 0, 51));
        afourth.setText("ALL FOURTH YEAR");
        afourth.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        afourth.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        afourth.setIconTextGap(10);
        afourth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afourthActionPerformed(evt);
            }
        });

        airreg.setBackground(new java.awt.Color(252, 227, 242));
        airreg.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        airreg.setForeground(new java.awt.Color(51, 0, 51));
        airreg.setText("ALL IRREGULAR");
        airreg.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        airreg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        airreg.setIconTextGap(10);
        airreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airregActionPerformed(evt);
            }
        });

        acrim.setBackground(new java.awt.Color(252, 227, 242));
        acrim.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        acrim.setForeground(new java.awt.Color(51, 0, 51));
        acrim.setText("ALL CRIMINOLOGY STUDENT");
        acrim.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        acrim.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        acrim.setIconTextGap(10);
        acrim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acrimActionPerformed(evt);
            }
        });

        aeduc.setBackground(new java.awt.Color(252, 227, 242));
        aeduc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        aeduc.setForeground(new java.awt.Color(51, 0, 51));
        aeduc.setText("ALL EDUCATION STUDENT");
        aeduc.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        aeduc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        aeduc.setIconTextGap(10);
        aeduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aeducActionPerformed(evt);
            }
        });

        aitct.setBackground(new java.awt.Color(252, 227, 242));
        aitct.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        aitct.setForeground(new java.awt.Color(51, 0, 51));
        aitct.setText("ALL INFO-TECH/CT STUDENT");
        aitct.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        aitct.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        aitct.setIconTextGap(10);
        aitct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aitctActionPerformed(evt);
            }
        });

        absba.setBackground(new java.awt.Color(252, 227, 242));
        absba.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        absba.setForeground(new java.awt.Color(51, 0, 51));
        absba.setText("ALL BSBA STUDENT");
        absba.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        absba.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        absba.setIconTextGap(10);
        absba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absbaActionPerformed(evt);
            }
        });

        afi.setBackground(new java.awt.Color(252, 227, 242));
        afi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        afi.setForeground(new java.awt.Color(51, 0, 51));
        afi.setText("ALL FISHERY STUDENT");
        afi.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        afi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        afi.setIconTextGap(10);
        afi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(astudents)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(afirst)
                            .addComponent(asecond)
                            .addComponent(athird)
                            .addComponent(afourth)
                            .addComponent(airreg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(afi)
                            .addComponent(absba)
                            .addComponent(aitct)
                            .addComponent(aeduc)
                            .addComponent(acrim))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(astudents)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(afirst)
                    .addComponent(acrim))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asecond)
                    .addComponent(aeduc))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(athird)
                    .addComponent(aitct))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(afourth)
                    .addComponent(absba))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airreg)
                    .addComponent(afi))
                .addContainerGap())
        );

        tabto.addTab("STUDENTS", jPanel2);

        ins_all.setBackground(new java.awt.Color(252, 227, 242));
        ins_all.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ins_all.setForeground(new java.awt.Color(51, 0, 51));
        ins_all.setText("ALL TEACHERS");
        ins_all.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        ins_all.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ins_all.setIconTextGap(10);
        ins_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_allActionPerformed(evt);
            }
        });

        ins_parttime.setBackground(new java.awt.Color(252, 227, 242));
        ins_parttime.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ins_parttime.setForeground(new java.awt.Color(51, 0, 51));
        ins_parttime.setText("ALL PART TIME");
        ins_parttime.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        ins_parttime.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ins_parttime.setIconTextGap(10);
        ins_parttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_parttimeActionPerformed(evt);
            }
        });

        ins_regular.setBackground(new java.awt.Color(252, 227, 242));
        ins_regular.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ins_regular.setForeground(new java.awt.Color(51, 0, 51));
        ins_regular.setText("ALL REGULARS");
        ins_regular.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        ins_regular.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ins_regular.setIconTextGap(10);
        ins_regular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_regularActionPerformed(evt);
            }
        });

        ins_crim.setBackground(new java.awt.Color(252, 227, 242));
        ins_crim.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ins_crim.setForeground(new java.awt.Color(51, 0, 51));
        ins_crim.setText("ALL CRIMINOLOGY FACULTY");
        ins_crim.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        ins_crim.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ins_crim.setIconTextGap(10);
        ins_crim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_crimActionPerformed(evt);
            }
        });

        ins_educ.setBackground(new java.awt.Color(252, 227, 242));
        ins_educ.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ins_educ.setForeground(new java.awt.Color(51, 0, 51));
        ins_educ.setText("ALL EDUCATION FACULTY");
        ins_educ.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        ins_educ.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ins_educ.setIconTextGap(10);
        ins_educ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_educActionPerformed(evt);
            }
        });

        ins_itct.setBackground(new java.awt.Color(252, 227, 242));
        ins_itct.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ins_itct.setForeground(new java.awt.Color(51, 0, 51));
        ins_itct.setText("ALL IT/CT FACULTY");
        ins_itct.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        ins_itct.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ins_itct.setIconTextGap(10);
        ins_itct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_itctActionPerformed(evt);
            }
        });

        ins_bsba.setBackground(new java.awt.Color(252, 227, 242));
        ins_bsba.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ins_bsba.setForeground(new java.awt.Color(51, 0, 51));
        ins_bsba.setText("ALL BSBA FACULTY");
        ins_bsba.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        ins_bsba.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ins_bsba.setIconTextGap(10);
        ins_bsba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_bsbaActionPerformed(evt);
            }
        });

        ins_fi.setBackground(new java.awt.Color(252, 227, 242));
        ins_fi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ins_fi.setForeground(new java.awt.Color(51, 0, 51));
        ins_fi.setText("ALL FISHERY FACULTY");
        ins_fi.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        ins_fi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ins_fi.setIconTextGap(10);
        ins_fi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_fiActionPerformed(evt);
            }
        });

        ins_staff.setBackground(new java.awt.Color(252, 227, 242));
        ins_staff.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ins_staff.setForeground(new java.awt.Color(51, 0, 51));
        ins_staff.setText("ALLSTAFF");
        ins_staff.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        ins_staff.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ins_staff.setIconTextGap(10);
        ins_staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_staffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ins_parttime)
                        .addGap(18, 18, 18)
                        .addComponent(ins_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ins_regular, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(ins_all))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ins_crim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ins_educ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ins_itct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ins_bsba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ins_fi, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ins_all)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ins_parttime)
                    .addComponent(ins_regular)
                    .addComponent(ins_staff))
                .addGap(18, 18, 18)
                .addComponent(ins_crim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ins_educ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ins_itct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ins_bsba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ins_fi)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tabto.addTab("TEACHERS", jPanel3);

        officers_all.setBackground(new java.awt.Color(252, 227, 242));
        officers_all.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        officers_all.setForeground(new java.awt.Color(51, 0, 51));
        officers_all.setText("ALL OFFIRCERS");
        officers_all.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        officers_all.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        officers_all.setIconTextGap(10);
        officers_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                officers_allActionPerformed(evt);
            }
        });

        ossg.setBackground(new java.awt.Color(252, 227, 242));
        ossg.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ossg.setForeground(new java.awt.Color(51, 0, 51));
        ossg.setText("SSG OFFIRCERS");
        ossg.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        ossg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ossg.setIconTextGap(10);
        ossg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ossgActionPerformed(evt);
            }
        });

        ouso.setBackground(new java.awt.Color(252, 227, 242));
        ouso.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ouso.setForeground(new java.awt.Color(51, 0, 51));
        ouso.setText("USO OFFIRCERS");
        ouso.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        ouso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ouso.setIconTextGap(10);
        ouso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ousoActionPerformed(evt);
            }
        });

        oaquarian.setBackground(new java.awt.Color(252, 227, 242));
        oaquarian.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        oaquarian.setForeground(new java.awt.Color(51, 0, 51));
        oaquarian.setText("AQUARIAN OFFIRCERS");
        oaquarian.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        oaquarian.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        oaquarian.setIconTextGap(10);
        oaquarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oaquarianActionPerformed(evt);
            }
        });

        orotc.setBackground(new java.awt.Color(252, 227, 242));
        orotc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        orotc.setForeground(new java.awt.Color(51, 0, 51));
        orotc.setText("ROTC OFFIRCERS");
        orotc.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        orotc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        orotc.setIconTextGap(10);
        orotc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orotcActionPerformed(evt);
            }
        });

        oclass.setBackground(new java.awt.Color(252, 227, 242));
        oclass.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        oclass.setForeground(new java.awt.Color(51, 0, 51));
        oclass.setText("CLASSROOM OFFIRCERS");
        oclass.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        oclass.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        oclass.setIconTextGap(10);
        oclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oclassActionPerformed(evt);
            }
        });

        oassap.setBackground(new java.awt.Color(252, 227, 242));
        oassap.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        oassap.setForeground(new java.awt.Color(51, 0, 51));
        oassap.setText("ASSAP OFFIRCERS");
        oassap.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        oassap.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        oassap.setIconTextGap(10);
        oassap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oassapActionPerformed(evt);
            }
        });

        oteso.setBackground(new java.awt.Color(252, 227, 242));
        oteso.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        oteso.setForeground(new java.awt.Color(51, 0, 51));
        oteso.setText("TESO OFFIRCERS");
        oteso.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        oteso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        oteso.setIconTextGap(10);
        oteso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otesoActionPerformed(evt);
            }
        });

        ofiso.setBackground(new java.awt.Color(252, 227, 242));
        ofiso.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ofiso.setForeground(new java.awt.Color(51, 0, 51));
        ofiso.setText("FISO OFFIRCERS");
        ofiso.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        ofiso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ofiso.setIconTextGap(10);
        ofiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ofisoActionPerformed(evt);
            }
        });

        owbm.setBackground(new java.awt.Color(252, 227, 242));
        owbm.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        owbm.setForeground(new java.awt.Color(51, 0, 51));
        owbm.setText("WBM OFFIRCERS");
        owbm.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        owbm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        owbm.setIconTextGap(10);
        owbm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                owbmActionPerformed(evt);
            }
        });

        opsits.setBackground(new java.awt.Color(252, 227, 242));
        opsits.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        opsits.setForeground(new java.awt.Color(51, 0, 51));
        opsits.setText("PSITS OFFIRCERS");
        opsits.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        opsits.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        opsits.setIconTextGap(10);
        opsits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opsitsActionPerformed(evt);
            }
        });

        ocrim.setBackground(new java.awt.Color(252, 227, 242));
        ocrim.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ocrim.setForeground(new java.awt.Color(51, 0, 51));
        ocrim.setText("K3 OFFIRCERS");
        ocrim.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        ocrim.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ocrim.setIconTextGap(10);
        ocrim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocrimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oteso)
                    .addComponent(ofiso)
                    .addComponent(owbm)
                    .addComponent(opsits)
                    .addComponent(ocrim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ouso)
                    .addComponent(ossg)
                    .addComponent(orotc)
                    .addComponent(oassap)
                    .addComponent(oaquarian))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(oclass)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(officers_all)
                .addGap(175, 175, 175))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(officers_all)
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ossg)
                    .addComponent(oteso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ouso)
                    .addComponent(ofiso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orotc)
                    .addComponent(owbm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oassap)
                    .addComponent(opsits))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oaquarian)
                    .addComponent(ocrim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(oclass)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tabto.addTab("OFFICERS", jPanel4);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("ADD MESSAGE");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tx_all.setBackground(new java.awt.Color(252, 227, 242));
        tx_all.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tx_all.setForeground(new java.awt.Color(51, 0, 51));
        tx_all.setText("ALL STUDENTS, TEACHERS & OFFICERS");
        tx_all.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        tx_all.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tx_all.setIconTextGap(10);
        tx_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_allActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(255, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tx_all, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tabto, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabto, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx_all))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabtoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabtoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabtoMouseClicked

    private void ins_crimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_crimActionPerformed
ins_all.setSelected(false);
tx_all.setSelected(false);            // TODO add your handling code here:
    }//GEN-LAST:event_ins_crimActionPerformed

    private void ins_educActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_educActionPerformed
ins_all.setSelected(false);
tx_all.setSelected(false);            // TODO add your handling code here:
    }//GEN-LAST:event_ins_educActionPerformed

    private void ins_itctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_itctActionPerformed
ins_all.setSelected(false);
tx_all.setSelected(false);            // TODO add your handling code here:
    }//GEN-LAST:event_ins_itctActionPerformed

    private void ins_bsbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_bsbaActionPerformed
ins_all.setSelected(false);
tx_all.setSelected(false);        }//GEN-LAST:event_ins_bsbaActionPerformed

    private void ins_fiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_fiActionPerformed
ins_all.setSelected(false);
tx_all.setSelected(false);            // TODO add your handling code here:
    }//GEN-LAST:event_ins_fiActionPerformed

    private void ins_staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_staffActionPerformed
ins_all.setSelected(false);
tx_all.setSelected(false);    
        // TODO add your handling code here:
    }//GEN-LAST:event_ins_staffActionPerformed

    private void astudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_astudentsActionPerformed
        if (astudents.isSelected()) {
            afirst.setSelected(true);
            asecond.setSelected(true);
            athird.setSelected(true);
            afourth.setSelected(true);
            airreg.setSelected(true);
            acrim.setSelected(true);
            aeduc.setSelected(true);
            aitct.setSelected(true);
            absba.setSelected(true);
            afi.setSelected(true);
        } else {
            afirst.setSelected(false);
            asecond.setSelected(false);
            athird.setSelected(false);
            afourth.setSelected(false);
            airreg.setSelected(false);
            acrim.setSelected(false);
            aeduc.setSelected(false);
            aitct.setSelected(false);
            absba.setSelected(false);
            afi.setSelected(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_astudentsActionPerformed

    private void astudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_astudentsMouseClicked

// TODO add your handling code here:
    }//GEN-LAST:event_astudentsMouseClicked

    private void officers_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_officers_allActionPerformed

        if (officers_all.isSelected()) {
            oteso.setSelected(true);
            ofiso.setSelected(true);
            opsits.setSelected(true);
            owbm.setSelected(true);
            ocrim.setSelected(true);
            ossg.setSelected(true);
            ouso.setSelected(true);
            oaquarian.setSelected(true);
            oassap.setSelected(true);
            orotc.setSelected(true);
            oclass.setSelected(true);
        } else {
            oteso.setSelected(false);
            ofiso.setSelected(false);
            opsits.setSelected(false);
            owbm.setSelected(false);
            ocrim.setSelected(false);
            ossg.setSelected(false);
            ouso.setSelected(false);
            oaquarian.setSelected(false);
            oassap.setSelected(false);
            orotc.setSelected(false);
            oclass.setSelected(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_officers_allActionPerformed

    private void ossgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ossgActionPerformed
officers_all.setSelected(false);
tx_all.setSelected(false);         // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_ossgActionPerformed

    private void ousoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ousoActionPerformed
officers_all.setSelected(false);
tx_all.setSelected(false);         // TODO add your handling code here:
    }//GEN-LAST:event_ousoActionPerformed

    private void oaquarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oaquarianActionPerformed
officers_all.setSelected(false);
tx_all.setSelected(false);         // TODO add your handling code here:
    }//GEN-LAST:event_oaquarianActionPerformed

    private void orotcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orotcActionPerformed
officers_all.setSelected(false);
tx_all.setSelected(false);         // TODO add your handling code here:
    }//GEN-LAST:event_orotcActionPerformed

    private void oclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oclassActionPerformed
officers_all.setSelected(false);
tx_all.setSelected(false);         // TODO add your handling code here:
    }//GEN-LAST:event_oclassActionPerformed

    private void oassapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oassapActionPerformed
officers_all.setSelected(false);
tx_all.setSelected(false);         // TODO add your handling code here:
    }//GEN-LAST:event_oassapActionPerformed

    private void otesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otesoActionPerformed
officers_all.setSelected(false);
tx_all.setSelected(false);            // TODO add your handling code here:
    }//GEN-LAST:event_otesoActionPerformed

    private void ofisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ofisoActionPerformed
officers_all.setSelected(false);
tx_all.setSelected(false);         // TODO add your handling code here:
    }//GEN-LAST:event_ofisoActionPerformed

    private void owbmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_owbmActionPerformed
officers_all.setSelected(false);
tx_all.setSelected(false);         // TODO add your handling code here:
    }//GEN-LAST:event_owbmActionPerformed

    private void opsitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opsitsActionPerformed
officers_all.setSelected(false);
tx_all.setSelected(false);         // TODO add your handling code here:
    }//GEN-LAST:event_opsitsActionPerformed

    private void ocrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocrimActionPerformed
officers_all.setSelected(false);
tx_all.setSelected(false);         // TODO add your handling code here:
    }//GEN-LAST:event_ocrimActionPerformed

    private void tx_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_allActionPerformed
        if (tx_all.isSelected()) {
            astudents.setSelected(true);
            afirst.setSelected(true);
            asecond.setSelected(true);
            athird.setSelected(true);
            afourth.setSelected(true);
            airreg.setSelected(true);
            acrim.setSelected(true);
            aeduc.setSelected(true);
            aitct.setSelected(true);
            absba.setSelected(true);
            afi.setSelected(true);

            ins_all.setSelected(true);
            ins_parttime.setSelected(true);
            ins_staff.setSelected(true);
            ins_regular.setSelected(true);
            ins_crim.setSelected(true);
            ins_educ.setSelected(true);
            ins_itct.setSelected(true);
            ins_bsba.setSelected(true);
            ins_fi.setSelected(true);

            officers_all.setSelected(true);
            oteso.setSelected(true);
            ofiso.setSelected(true);
            opsits.setSelected(true);
            owbm.setSelected(true);
            ocrim.setSelected(true);
            ossg.setSelected(true);
            ouso.setSelected(true);
            oaquarian.setSelected(true);
            oassap.setSelected(true);
            orotc.setSelected(true);
            oclass.setSelected(true);
        } else {
            ins_all.setSelected(false);
            ins_parttime.setSelected(false);
            ins_staff.setSelected(false);
            ins_regular.setSelected(false);
            ins_crim.setSelected(false);
            ins_educ.setSelected(false);
            ins_itct.setSelected(false);
            ins_bsba.setSelected(false);
            ins_fi.setSelected(false);

            officers_all.setSelected(false);
            oteso.setSelected(false);
            ofiso.setSelected(false);
            opsits.setSelected(false);
            owbm.setSelected(false);
            ocrim.setSelected(false);
            ossg.setSelected(false);
            ouso.setSelected(false);
            oaquarian.setSelected(false);
            oassap.setSelected(false);
            orotc.setSelected(false);
            oclass.setSelected(false);

            astudents.setSelected(false);
            afirst.setSelected(false);
            asecond.setSelected(false);
            athird.setSelected(false);
            afourth.setSelected(false);
            airreg.setSelected(false);
            acrim.setSelected(false);
            aeduc.setSelected(false);
            aitct.setSelected(false);
            absba.setSelected(false);
            afi.setSelected(false);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_tx_allActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (afirst.isSelected()) {
            sendan = sendan + "hhdhd   ";
        }
        if (asecond.isSelected()) {
            sendan = sendan + "hhdhdsdfghjkl   ";
        }
        jLabel1.setText(sendan);
        System.out.println(sendan);
        to.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ins_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_allActionPerformed
        if (ins_all.isSelected()) {
            ins_parttime.setSelected(true);
            ins_staff.setSelected(true);
            ins_regular.setSelected(true);
            ins_crim.setSelected(true);
            ins_educ.setSelected(true);
            ins_itct.setSelected(true);
            ins_bsba.setSelected(true);
            ins_fi.setSelected(true);
        } else {
            ins_parttime.setSelected(false);
            ins_staff.setSelected(false);
            ins_regular.setSelected(false);
            ins_crim.setSelected(false);
            ins_educ.setSelected(false);
            ins_itct.setSelected(false);
            ins_bsba.setSelected(false);
            ins_fi.setSelected(false);
        }
    }//GEN-LAST:event_ins_allActionPerformed

    private void afirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afirstActionPerformed
astudents.setSelected(false);
tx_all.setSelected(false);       
        
    }//GEN-LAST:event_afirstActionPerformed

    private void asecondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asecondActionPerformed
astudents.setSelected(false);
tx_all.setSelected(false);          // TODO add your handling code here:
    }//GEN-LAST:event_asecondActionPerformed

    private void athirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_athirdActionPerformed
astudents.setSelected(false);
tx_all.setSelected(false);          // TODO add your handling code here:
    }//GEN-LAST:event_athirdActionPerformed

    private void afourthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afourthActionPerformed
astudents.setSelected(false);
tx_all.setSelected(false);          // TODO add your handling code here:
    }//GEN-LAST:event_afourthActionPerformed

    private void airregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airregActionPerformed
astudents.setSelected(false);
tx_all.setSelected(false);          // TODO add your handling code here:
    }//GEN-LAST:event_airregActionPerformed

    private void acrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acrimActionPerformed
astudents.setSelected(false);
tx_all.setSelected(false);          // TODO add your handling code here:
    }//GEN-LAST:event_acrimActionPerformed

    private void aeducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aeducActionPerformed
astudents.setSelected(false);
tx_all.setSelected(false);          // TODO add your handling code here:
    }//GEN-LAST:event_aeducActionPerformed

    private void aitctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aitctActionPerformed
astudents.setSelected(false);
tx_all.setSelected(false);          // TODO add your handling code here:
    }//GEN-LAST:event_aitctActionPerformed

    private void absbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absbaActionPerformed
astudents.setSelected(false);
tx_all.setSelected(false);          // TODO add your handling code here:
    }//GEN-LAST:event_absbaActionPerformed

    private void afiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afiActionPerformed
astudents.setSelected(false);
tx_all.setSelected(false);          // TODO add your handling code here:
    }//GEN-LAST:event_afiActionPerformed

    private void ins_parttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_parttimeActionPerformed
ins_all.setSelected(false);
tx_all.setSelected(false);          // TODO add your handling code here:
    }//GEN-LAST:event_ins_parttimeActionPerformed

    private void ins_regularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_regularActionPerformed
ins_all.setSelected(false);
tx_all.setSelected(false);            // TODO add your handling code here:
    }//GEN-LAST:event_ins_regularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tecx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tecx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tecx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tecx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tecx().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox absba;
    private javax.swing.JCheckBox acrim;
    private javax.swing.JCheckBox aeduc;
    private javax.swing.JCheckBox afi;
    private javax.swing.JCheckBox afirst;
    private javax.swing.JCheckBox afourth;
    private javax.swing.JCheckBox airreg;
    private javax.swing.JCheckBox aitct;
    private javax.swing.JCheckBox asecond;
    private javax.swing.JCheckBox astudents;
    private javax.swing.JCheckBox athird;
    private javax.swing.JCheckBox ins_all;
    private javax.swing.JCheckBox ins_bsba;
    private javax.swing.JCheckBox ins_crim;
    private javax.swing.JCheckBox ins_educ;
    private javax.swing.JCheckBox ins_fi;
    private javax.swing.JCheckBox ins_itct;
    private javax.swing.JCheckBox ins_parttime;
    private javax.swing.JCheckBox ins_regular;
    private javax.swing.JCheckBox ins_staff;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JCheckBox oaquarian;
    private javax.swing.JCheckBox oassap;
    private javax.swing.JCheckBox oclass;
    private javax.swing.JCheckBox ocrim;
    private javax.swing.JCheckBox officers_all;
    private javax.swing.JCheckBox ofiso;
    private javax.swing.JCheckBox opsits;
    private javax.swing.JCheckBox orotc;
    private javax.swing.JCheckBox ossg;
    private javax.swing.JCheckBox oteso;
    private javax.swing.JCheckBox ouso;
    private javax.swing.JCheckBox owbm;
    private javax.swing.JTabbedPane tabto;
    private javax.swing.JDialog to;
    private javax.swing.JCheckBox tx_all;
    // End of variables declaration//GEN-END:variables
public String sendan;
}
